name: Test filter
on: [push]
jobs:
  test-verbatim-captioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: (cd test/verbatim-captioning && sh test.sh)
  test-pandoc-latex-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: (cd test/pandoc-latex-env && sh test.sh)

          
