name: Test filter
on: [push]
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Move to test
        run: cd test
      - name: pull image
        run: docker pull ngocptblaplafla/pandoc-texlive-full:latest
  test-verbatim-captioning:
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - run: (cd verbatim-captioning && sh test.sh)

          
